// Code generated by protoc-gen-go.
// source: cstrike15_usermessages_public.proto
// DO NOT EDIT!

/*
Package cstrike15_usermessages_public is a generated protocol buffer package.

It is generated from these files:
	cstrike15_usermessages_public.proto

It has these top-level messages:
	CCSUsrMsg_VGUIMenu
	CCSUsrMsg_Geiger
	CCSUsrMsg_Train
	CCSUsrMsg_HudText
	CCSUsrMsg_SayText
	CCSUsrMsg_SayText2
	CCSUsrMsg_TextMsg
	CCSUsrMsg_HudMsg
	CCSUsrMsg_Shake
	CCSUsrMsg_Fade
	CCSUsrMsg_Rumble
	CCSUsrMsg_CloseCaption
	CCSUsrMsg_CloseCaptionDirect
	CCSUsrMsg_SendAudio
	CCSUsrMsg_RawAudio
	CCSUsrMsg_VoiceMask
	CCSUsrMsg_Damage
	CCSUsrMsg_RadioText
	CCSUsrMsg_HintText
	CCSUsrMsg_KeyHintText
	CCSUsrMsg_ProcessSpottedEntityUpdate
	CCSUsrMsg_ReloadEffect
	CCSUsrMsg_AdjustMoney
	CCSUsrMsg_KillCam
	CCSUsrMsg_DesiredTimescale
	CCSUsrMsg_CurrentTimescale
	CCSUsrMsg_AchievementEvent
	CCSUsrMsg_MatchEndConditions
	CCSUsrMsg_DisplayInventory
	CCSUsrMsg_CallVoteFailed
	CCSUsrMsg_VoteStart
	CCSUsrMsg_VotePass
	CCSUsrMsg_VoteFailed
	CCSUsrMsg_VoteSetup
	CCSUsrMsg_SendLastKillerDamageToClient
	CCSUsrMsg_ItemPickup
	CCSUsrMsg_ShowMenu
	CCSUsrMsg_BarTime
	CCSUsrMsg_AmmoDenied
	CCSUsrMsg_MarkAchievement
	CCSUsrMsg_ItemDrop
	CCSUsrMsg_GlowPropTurnOff
	CCSUsrMsg_RoundBackupFilenames
	CCSUsrMsg_ResetHud
	CCSUsrMsg_GameTitle
	CCSUsrMsg_RequestState
	CCSUsrMsg_StopSpectatorMode
	CCSUsrMsg_DisconnectToLobby
	CCSUsrMsg_WarmupHasEnded
	CCSUsrMsg_ClientInfo
*/
package cstrike15_usermessages_public

import proto "github.com/golang/protobuf/proto"
import math "math"

// discarding unused import google_protobuf "google/protobuf/descriptor.pb"
import netmessages_public "netmessages_public.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ECstrike15UserMessages int32

const (
	ECstrike15UserMessages_CS_UM_VGUIMenu                     ECstrike15UserMessages = 1
	ECstrike15UserMessages_CS_UM_Geiger                       ECstrike15UserMessages = 2
	ECstrike15UserMessages_CS_UM_Train                        ECstrike15UserMessages = 3
	ECstrike15UserMessages_CS_UM_HudText                      ECstrike15UserMessages = 4
	ECstrike15UserMessages_CS_UM_SayText                      ECstrike15UserMessages = 5
	ECstrike15UserMessages_CS_UM_SayText2                     ECstrike15UserMessages = 6
	ECstrike15UserMessages_CS_UM_TextMsg                      ECstrike15UserMessages = 7
	ECstrike15UserMessages_CS_UM_HudMsg                       ECstrike15UserMessages = 8
	ECstrike15UserMessages_CS_UM_ResetHud                     ECstrike15UserMessages = 9
	ECstrike15UserMessages_CS_UM_GameTitle                    ECstrike15UserMessages = 10
	ECstrike15UserMessages_CS_UM_Shake                        ECstrike15UserMessages = 12
	ECstrike15UserMessages_CS_UM_Fade                         ECstrike15UserMessages = 13
	ECstrike15UserMessages_CS_UM_Rumble                       ECstrike15UserMessages = 14
	ECstrike15UserMessages_CS_UM_CloseCaption                 ECstrike15UserMessages = 15
	ECstrike15UserMessages_CS_UM_CloseCaptionDirect           ECstrike15UserMessages = 16
	ECstrike15UserMessages_CS_UM_SendAudio                    ECstrike15UserMessages = 17
	ECstrike15UserMessages_CS_UM_RawAudio                     ECstrike15UserMessages = 18
	ECstrike15UserMessages_CS_UM_VoiceMask                    ECstrike15UserMessages = 19
	ECstrike15UserMessages_CS_UM_RequestState                 ECstrike15UserMessages = 20
	ECstrike15UserMessages_CS_UM_Damage                       ECstrike15UserMessages = 21
	ECstrike15UserMessages_CS_UM_RadioText                    ECstrike15UserMessages = 22
	ECstrike15UserMessages_CS_UM_HintText                     ECstrike15UserMessages = 23
	ECstrike15UserMessages_CS_UM_KeyHintText                  ECstrike15UserMessages = 24
	ECstrike15UserMessages_CS_UM_ProcessSpottedEntityUpdate   ECstrike15UserMessages = 25
	ECstrike15UserMessages_CS_UM_ReloadEffect                 ECstrike15UserMessages = 26
	ECstrike15UserMessages_CS_UM_AdjustMoney                  ECstrike15UserMessages = 27
	ECstrike15UserMessages_CS_UM_UpdateTeamMoney              ECstrike15UserMessages = 28
	ECstrike15UserMessages_CS_UM_StopSpectatorMode            ECstrike15UserMessages = 29
	ECstrike15UserMessages_CS_UM_KillCam                      ECstrike15UserMessages = 30
	ECstrike15UserMessages_CS_UM_DesiredTimescale             ECstrike15UserMessages = 31
	ECstrike15UserMessages_CS_UM_CurrentTimescale             ECstrike15UserMessages = 32
	ECstrike15UserMessages_CS_UM_AchievementEvent             ECstrike15UserMessages = 33
	ECstrike15UserMessages_CS_UM_MatchEndConditions           ECstrike15UserMessages = 34
	ECstrike15UserMessages_CS_UM_DisconnectToLobby            ECstrike15UserMessages = 35
	ECstrike15UserMessages_CS_UM_DisplayInventory             ECstrike15UserMessages = 37
	ECstrike15UserMessages_CS_UM_WarmupHasEnded               ECstrike15UserMessages = 38
	ECstrike15UserMessages_CS_UM_ClientInfo                   ECstrike15UserMessages = 39
	ECstrike15UserMessages_CS_UM_CallVoteFailed               ECstrike15UserMessages = 45
	ECstrike15UserMessages_CS_UM_VoteStart                    ECstrike15UserMessages = 46
	ECstrike15UserMessages_CS_UM_VotePass                     ECstrike15UserMessages = 47
	ECstrike15UserMessages_CS_UM_VoteFailed                   ECstrike15UserMessages = 48
	ECstrike15UserMessages_CS_UM_VoteSetup                    ECstrike15UserMessages = 49
	ECstrike15UserMessages_CS_UM_SendLastKillerDamageToClient ECstrike15UserMessages = 51
	ECstrike15UserMessages_CS_UM_ItemPickup                   ECstrike15UserMessages = 53
	ECstrike15UserMessages_CS_UM_ShowMenu                     ECstrike15UserMessages = 54
	ECstrike15UserMessages_CS_UM_BarTime                      ECstrike15UserMessages = 55
	ECstrike15UserMessages_CS_UM_AmmoDenied                   ECstrike15UserMessages = 56
	ECstrike15UserMessages_CS_UM_MarkAchievement              ECstrike15UserMessages = 57
	ECstrike15UserMessages_CS_UM_ItemDrop                     ECstrike15UserMessages = 59
	ECstrike15UserMessages_CS_UM_GlowPropTurnOff              ECstrike15UserMessages = 60
)

var ECstrike15UserMessages_name = map[int32]string{
	1:  "CS_UM_VGUIMenu",
	2:  "CS_UM_Geiger",
	3:  "CS_UM_Train",
	4:  "CS_UM_HudText",
	5:  "CS_UM_SayText",
	6:  "CS_UM_SayText2",
	7:  "CS_UM_TextMsg",
	8:  "CS_UM_HudMsg",
	9:  "CS_UM_ResetHud",
	10: "CS_UM_GameTitle",
	12: "CS_UM_Shake",
	13: "CS_UM_Fade",
	14: "CS_UM_Rumble",
	15: "CS_UM_CloseCaption",
	16: "CS_UM_CloseCaptionDirect",
	17: "CS_UM_SendAudio",
	18: "CS_UM_RawAudio",
	19: "CS_UM_VoiceMask",
	20: "CS_UM_RequestState",
	21: "CS_UM_Damage",
	22: "CS_UM_RadioText",
	23: "CS_UM_HintText",
	24: "CS_UM_KeyHintText",
	25: "CS_UM_ProcessSpottedEntityUpdate",
	26: "CS_UM_ReloadEffect",
	27: "CS_UM_AdjustMoney",
	28: "CS_UM_UpdateTeamMoney",
	29: "CS_UM_StopSpectatorMode",
	30: "CS_UM_KillCam",
	31: "CS_UM_DesiredTimescale",
	32: "CS_UM_CurrentTimescale",
	33: "CS_UM_AchievementEvent",
	34: "CS_UM_MatchEndConditions",
	35: "CS_UM_DisconnectToLobby",
	37: "CS_UM_DisplayInventory",
	38: "CS_UM_WarmupHasEnded",
	39: "CS_UM_ClientInfo",
	45: "CS_UM_CallVoteFailed",
	46: "CS_UM_VoteStart",
	47: "CS_UM_VotePass",
	48: "CS_UM_VoteFailed",
	49: "CS_UM_VoteSetup",
	51: "CS_UM_SendLastKillerDamageToClient",
	53: "CS_UM_ItemPickup",
	54: "CS_UM_ShowMenu",
	55: "CS_UM_BarTime",
	56: "CS_UM_AmmoDenied",
	57: "CS_UM_MarkAchievement",
	59: "CS_UM_ItemDrop",
	60: "CS_UM_GlowPropTurnOff",
}
var ECstrike15UserMessages_value = map[string]int32{
	"CS_UM_VGUIMenu":                     1,
	"CS_UM_Geiger":                       2,
	"CS_UM_Train":                        3,
	"CS_UM_HudText":                      4,
	"CS_UM_SayText":                      5,
	"CS_UM_SayText2":                     6,
	"CS_UM_TextMsg":                      7,
	"CS_UM_HudMsg":                       8,
	"CS_UM_ResetHud":                     9,
	"CS_UM_GameTitle":                    10,
	"CS_UM_Shake":                        12,
	"CS_UM_Fade":                         13,
	"CS_UM_Rumble":                       14,
	"CS_UM_CloseCaption":                 15,
	"CS_UM_CloseCaptionDirect":           16,
	"CS_UM_SendAudio":                    17,
	"CS_UM_RawAudio":                     18,
	"CS_UM_VoiceMask":                    19,
	"CS_UM_RequestState":                 20,
	"CS_UM_Damage":                       21,
	"CS_UM_RadioText":                    22,
	"CS_UM_HintText":                     23,
	"CS_UM_KeyHintText":                  24,
	"CS_UM_ProcessSpottedEntityUpdate":   25,
	"CS_UM_ReloadEffect":                 26,
	"CS_UM_AdjustMoney":                  27,
	"CS_UM_UpdateTeamMoney":              28,
	"CS_UM_StopSpectatorMode":            29,
	"CS_UM_KillCam":                      30,
	"CS_UM_DesiredTimescale":             31,
	"CS_UM_CurrentTimescale":             32,
	"CS_UM_AchievementEvent":             33,
	"CS_UM_MatchEndConditions":           34,
	"CS_UM_DisconnectToLobby":            35,
	"CS_UM_DisplayInventory":             37,
	"CS_UM_WarmupHasEnded":               38,
	"CS_UM_ClientInfo":                   39,
	"CS_UM_CallVoteFailed":               45,
	"CS_UM_VoteStart":                    46,
	"CS_UM_VotePass":                     47,
	"CS_UM_VoteFailed":                   48,
	"CS_UM_VoteSetup":                    49,
	"CS_UM_SendLastKillerDamageToClient": 51,
	"CS_UM_ItemPickup":                   53,
	"CS_UM_ShowMenu":                     54,
	"CS_UM_BarTime":                      55,
	"CS_UM_AmmoDenied":                   56,
	"CS_UM_MarkAchievement":              57,
	"CS_UM_ItemDrop":                     59,
	"CS_UM_GlowPropTurnOff":              60,
}

func (x ECstrike15UserMessages) Enum() *ECstrike15UserMessages {
	p := new(ECstrike15UserMessages)
	*p = x
	return p
}
func (x ECstrike15UserMessages) String() string {
	return proto.EnumName(ECstrike15UserMessages_name, int32(x))
}
func (x *ECstrike15UserMessages) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ECstrike15UserMessages_value, data, "ECstrike15UserMessages")
	if err != nil {
		return err
	}
	*x = ECstrike15UserMessages(value)
	return nil
}

type CCSUsrMsg_VGUIMenu struct {
	Name             *string                      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Show             *bool                        `protobuf:"varint,2,opt,name=show" json:"show,omitempty"`
	Subkeys          []*CCSUsrMsg_VGUIMenu_Subkey `protobuf:"bytes,3,rep,name=subkeys" json:"subkeys,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *CCSUsrMsg_VGUIMenu) Reset()         { *m = CCSUsrMsg_VGUIMenu{} }
func (m *CCSUsrMsg_VGUIMenu) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VGUIMenu) ProtoMessage()    {}

func (m *CCSUsrMsg_VGUIMenu) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CCSUsrMsg_VGUIMenu) GetShow() bool {
	if m != nil && m.Show != nil {
		return *m.Show
	}
	return false
}

func (m *CCSUsrMsg_VGUIMenu) GetSubkeys() []*CCSUsrMsg_VGUIMenu_Subkey {
	if m != nil {
		return m.Subkeys
	}
	return nil
}

type CCSUsrMsg_VGUIMenu_Subkey struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Str              *string `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_VGUIMenu_Subkey) Reset()         { *m = CCSUsrMsg_VGUIMenu_Subkey{} }
func (m *CCSUsrMsg_VGUIMenu_Subkey) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VGUIMenu_Subkey) ProtoMessage()    {}

func (m *CCSUsrMsg_VGUIMenu_Subkey) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CCSUsrMsg_VGUIMenu_Subkey) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

type CCSUsrMsg_Geiger struct {
	Range            *int32 `protobuf:"varint,1,opt,name=range" json:"range,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_Geiger) Reset()         { *m = CCSUsrMsg_Geiger{} }
func (m *CCSUsrMsg_Geiger) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_Geiger) ProtoMessage()    {}

func (m *CCSUsrMsg_Geiger) GetRange() int32 {
	if m != nil && m.Range != nil {
		return *m.Range
	}
	return 0
}

type CCSUsrMsg_Train struct {
	Train            *int32 `protobuf:"varint,1,opt,name=train" json:"train,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_Train) Reset()         { *m = CCSUsrMsg_Train{} }
func (m *CCSUsrMsg_Train) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_Train) ProtoMessage()    {}

func (m *CCSUsrMsg_Train) GetTrain() int32 {
	if m != nil && m.Train != nil {
		return *m.Train
	}
	return 0
}

type CCSUsrMsg_HudText struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_HudText) Reset()         { *m = CCSUsrMsg_HudText{} }
func (m *CCSUsrMsg_HudText) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_HudText) ProtoMessage()    {}

func (m *CCSUsrMsg_HudText) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type CCSUsrMsg_SayText struct {
	EntIdx           *int32  `protobuf:"varint,1,opt,name=ent_idx" json:"ent_idx,omitempty"`
	Text             *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Chat             *bool   `protobuf:"varint,3,opt,name=chat" json:"chat,omitempty"`
	Textallchat      *bool   `protobuf:"varint,4,opt,name=textallchat" json:"textallchat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_SayText) Reset()         { *m = CCSUsrMsg_SayText{} }
func (m *CCSUsrMsg_SayText) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_SayText) ProtoMessage()    {}

func (m *CCSUsrMsg_SayText) GetEntIdx() int32 {
	if m != nil && m.EntIdx != nil {
		return *m.EntIdx
	}
	return 0
}

func (m *CCSUsrMsg_SayText) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *CCSUsrMsg_SayText) GetChat() bool {
	if m != nil && m.Chat != nil {
		return *m.Chat
	}
	return false
}

func (m *CCSUsrMsg_SayText) GetTextallchat() bool {
	if m != nil && m.Textallchat != nil {
		return *m.Textallchat
	}
	return false
}

type CCSUsrMsg_SayText2 struct {
	EntIdx           *int32   `protobuf:"varint,1,opt,name=ent_idx" json:"ent_idx,omitempty"`
	Chat             *bool    `protobuf:"varint,2,opt,name=chat" json:"chat,omitempty"`
	MsgName          *string  `protobuf:"bytes,3,opt,name=msg_name" json:"msg_name,omitempty"`
	Params           []string `protobuf:"bytes,4,rep,name=params" json:"params,omitempty"`
	Textallchat      *bool    `protobuf:"varint,5,opt,name=textallchat" json:"textallchat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_SayText2) Reset()         { *m = CCSUsrMsg_SayText2{} }
func (m *CCSUsrMsg_SayText2) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_SayText2) ProtoMessage()    {}

func (m *CCSUsrMsg_SayText2) GetEntIdx() int32 {
	if m != nil && m.EntIdx != nil {
		return *m.EntIdx
	}
	return 0
}

func (m *CCSUsrMsg_SayText2) GetChat() bool {
	if m != nil && m.Chat != nil {
		return *m.Chat
	}
	return false
}

func (m *CCSUsrMsg_SayText2) GetMsgName() string {
	if m != nil && m.MsgName != nil {
		return *m.MsgName
	}
	return ""
}

func (m *CCSUsrMsg_SayText2) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *CCSUsrMsg_SayText2) GetTextallchat() bool {
	if m != nil && m.Textallchat != nil {
		return *m.Textallchat
	}
	return false
}

type CCSUsrMsg_TextMsg struct {
	MsgDst           *int32   `protobuf:"varint,1,opt,name=msg_dst" json:"msg_dst,omitempty"`
	Params           []string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_TextMsg) Reset()         { *m = CCSUsrMsg_TextMsg{} }
func (m *CCSUsrMsg_TextMsg) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_TextMsg) ProtoMessage()    {}

func (m *CCSUsrMsg_TextMsg) GetMsgDst() int32 {
	if m != nil && m.MsgDst != nil {
		return *m.MsgDst
	}
	return 0
}

func (m *CCSUsrMsg_TextMsg) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type CCSUsrMsg_HudMsg struct {
	Channel          *int32                           `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	Pos              *netmessages_public.CMsgVector2D `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	Clr1             *netmessages_public.CMsgRGBA     `protobuf:"bytes,3,opt,name=clr1" json:"clr1,omitempty"`
	Clr2             *netmessages_public.CMsgRGBA     `protobuf:"bytes,4,opt,name=clr2" json:"clr2,omitempty"`
	Effect           *int32                           `protobuf:"varint,5,opt,name=effect" json:"effect,omitempty"`
	FadeInTime       *float32                         `protobuf:"fixed32,6,opt,name=fade_in_time" json:"fade_in_time,omitempty"`
	FadeOutTime      *float32                         `protobuf:"fixed32,7,opt,name=fade_out_time" json:"fade_out_time,omitempty"`
	HoldTime         *float32                         `protobuf:"fixed32,9,opt,name=hold_time" json:"hold_time,omitempty"`
	FxTime           *float32                         `protobuf:"fixed32,10,opt,name=fx_time" json:"fx_time,omitempty"`
	Text             *string                          `protobuf:"bytes,11,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *CCSUsrMsg_HudMsg) Reset()         { *m = CCSUsrMsg_HudMsg{} }
func (m *CCSUsrMsg_HudMsg) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_HudMsg) ProtoMessage()    {}

func (m *CCSUsrMsg_HudMsg) GetChannel() int32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *CCSUsrMsg_HudMsg) GetPos() *netmessages_public.CMsgVector2D {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *CCSUsrMsg_HudMsg) GetClr1() *netmessages_public.CMsgRGBA {
	if m != nil {
		return m.Clr1
	}
	return nil
}

func (m *CCSUsrMsg_HudMsg) GetClr2() *netmessages_public.CMsgRGBA {
	if m != nil {
		return m.Clr2
	}
	return nil
}

func (m *CCSUsrMsg_HudMsg) GetEffect() int32 {
	if m != nil && m.Effect != nil {
		return *m.Effect
	}
	return 0
}

func (m *CCSUsrMsg_HudMsg) GetFadeInTime() float32 {
	if m != nil && m.FadeInTime != nil {
		return *m.FadeInTime
	}
	return 0
}

func (m *CCSUsrMsg_HudMsg) GetFadeOutTime() float32 {
	if m != nil && m.FadeOutTime != nil {
		return *m.FadeOutTime
	}
	return 0
}

func (m *CCSUsrMsg_HudMsg) GetHoldTime() float32 {
	if m != nil && m.HoldTime != nil {
		return *m.HoldTime
	}
	return 0
}

func (m *CCSUsrMsg_HudMsg) GetFxTime() float32 {
	if m != nil && m.FxTime != nil {
		return *m.FxTime
	}
	return 0
}

func (m *CCSUsrMsg_HudMsg) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type CCSUsrMsg_Shake struct {
	Command          *int32   `protobuf:"varint,1,opt,name=command" json:"command,omitempty"`
	LocalAmplitude   *float32 `protobuf:"fixed32,2,opt,name=local_amplitude" json:"local_amplitude,omitempty"`
	Frequency        *float32 `protobuf:"fixed32,3,opt,name=frequency" json:"frequency,omitempty"`
	Duration         *float32 `protobuf:"fixed32,4,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_Shake) Reset()         { *m = CCSUsrMsg_Shake{} }
func (m *CCSUsrMsg_Shake) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_Shake) ProtoMessage()    {}

func (m *CCSUsrMsg_Shake) GetCommand() int32 {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return 0
}

func (m *CCSUsrMsg_Shake) GetLocalAmplitude() float32 {
	if m != nil && m.LocalAmplitude != nil {
		return *m.LocalAmplitude
	}
	return 0
}

func (m *CCSUsrMsg_Shake) GetFrequency() float32 {
	if m != nil && m.Frequency != nil {
		return *m.Frequency
	}
	return 0
}

func (m *CCSUsrMsg_Shake) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type CCSUsrMsg_Fade struct {
	Duration         *int32                       `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
	HoldTime         *int32                       `protobuf:"varint,2,opt,name=hold_time" json:"hold_time,omitempty"`
	Flags            *int32                       `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	Clr              *netmessages_public.CMsgRGBA `protobuf:"bytes,4,opt,name=clr" json:"clr,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *CCSUsrMsg_Fade) Reset()         { *m = CCSUsrMsg_Fade{} }
func (m *CCSUsrMsg_Fade) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_Fade) ProtoMessage()    {}

func (m *CCSUsrMsg_Fade) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *CCSUsrMsg_Fade) GetHoldTime() int32 {
	if m != nil && m.HoldTime != nil {
		return *m.HoldTime
	}
	return 0
}

func (m *CCSUsrMsg_Fade) GetFlags() int32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CCSUsrMsg_Fade) GetClr() *netmessages_public.CMsgRGBA {
	if m != nil {
		return m.Clr
	}
	return nil
}

type CCSUsrMsg_Rumble struct {
	Index            *int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Data             *int32 `protobuf:"varint,2,opt,name=data" json:"data,omitempty"`
	Flags            *int32 `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_Rumble) Reset()         { *m = CCSUsrMsg_Rumble{} }
func (m *CCSUsrMsg_Rumble) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_Rumble) ProtoMessage()    {}

func (m *CCSUsrMsg_Rumble) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CCSUsrMsg_Rumble) GetData() int32 {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return 0
}

func (m *CCSUsrMsg_Rumble) GetFlags() int32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

type CCSUsrMsg_CloseCaption struct {
	Hash             *uint32 `protobuf:"varint,1,opt,name=hash" json:"hash,omitempty"`
	Duration         *int32  `protobuf:"varint,2,opt,name=duration" json:"duration,omitempty"`
	FromPlayer       *bool   `protobuf:"varint,3,opt,name=from_player" json:"from_player,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_CloseCaption) Reset()         { *m = CCSUsrMsg_CloseCaption{} }
func (m *CCSUsrMsg_CloseCaption) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_CloseCaption) ProtoMessage()    {}

func (m *CCSUsrMsg_CloseCaption) GetHash() uint32 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

func (m *CCSUsrMsg_CloseCaption) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *CCSUsrMsg_CloseCaption) GetFromPlayer() bool {
	if m != nil && m.FromPlayer != nil {
		return *m.FromPlayer
	}
	return false
}

type CCSUsrMsg_CloseCaptionDirect struct {
	Hash             *uint32 `protobuf:"varint,1,opt,name=hash" json:"hash,omitempty"`
	Duration         *int32  `protobuf:"varint,2,opt,name=duration" json:"duration,omitempty"`
	FromPlayer       *bool   `protobuf:"varint,3,opt,name=from_player" json:"from_player,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_CloseCaptionDirect) Reset()         { *m = CCSUsrMsg_CloseCaptionDirect{} }
func (m *CCSUsrMsg_CloseCaptionDirect) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_CloseCaptionDirect) ProtoMessage()    {}

func (m *CCSUsrMsg_CloseCaptionDirect) GetHash() uint32 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

func (m *CCSUsrMsg_CloseCaptionDirect) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *CCSUsrMsg_CloseCaptionDirect) GetFromPlayer() bool {
	if m != nil && m.FromPlayer != nil {
		return *m.FromPlayer
	}
	return false
}

type CCSUsrMsg_SendAudio struct {
	RadioSound       *string `protobuf:"bytes,1,opt,name=radio_sound" json:"radio_sound,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_SendAudio) Reset()         { *m = CCSUsrMsg_SendAudio{} }
func (m *CCSUsrMsg_SendAudio) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_SendAudio) ProtoMessage()    {}

func (m *CCSUsrMsg_SendAudio) GetRadioSound() string {
	if m != nil && m.RadioSound != nil {
		return *m.RadioSound
	}
	return ""
}

type CCSUsrMsg_RawAudio struct {
	Pitch            *int32   `protobuf:"varint,1,opt,name=pitch" json:"pitch,omitempty"`
	Entidx           *int32   `protobuf:"varint,2,opt,name=entidx" json:"entidx,omitempty"`
	Duration         *float32 `protobuf:"fixed32,3,opt,name=duration" json:"duration,omitempty"`
	VoiceFilename    *string  `protobuf:"bytes,4,opt,name=voice_filename" json:"voice_filename,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_RawAudio) Reset()         { *m = CCSUsrMsg_RawAudio{} }
func (m *CCSUsrMsg_RawAudio) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_RawAudio) ProtoMessage()    {}

func (m *CCSUsrMsg_RawAudio) GetPitch() int32 {
	if m != nil && m.Pitch != nil {
		return *m.Pitch
	}
	return 0
}

func (m *CCSUsrMsg_RawAudio) GetEntidx() int32 {
	if m != nil && m.Entidx != nil {
		return *m.Entidx
	}
	return 0
}

func (m *CCSUsrMsg_RawAudio) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *CCSUsrMsg_RawAudio) GetVoiceFilename() string {
	if m != nil && m.VoiceFilename != nil {
		return *m.VoiceFilename
	}
	return ""
}

type CCSUsrMsg_VoiceMask struct {
	PlayerMasks      []*CCSUsrMsg_VoiceMask_PlayerMask `protobuf:"bytes,1,rep,name=player_masks" json:"player_masks,omitempty"`
	PlayerModEnable  *bool                             `protobuf:"varint,2,opt,name=player_mod_enable" json:"player_mod_enable,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *CCSUsrMsg_VoiceMask) Reset()         { *m = CCSUsrMsg_VoiceMask{} }
func (m *CCSUsrMsg_VoiceMask) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VoiceMask) ProtoMessage()    {}

func (m *CCSUsrMsg_VoiceMask) GetPlayerMasks() []*CCSUsrMsg_VoiceMask_PlayerMask {
	if m != nil {
		return m.PlayerMasks
	}
	return nil
}

func (m *CCSUsrMsg_VoiceMask) GetPlayerModEnable() bool {
	if m != nil && m.PlayerModEnable != nil {
		return *m.PlayerModEnable
	}
	return false
}

type CCSUsrMsg_VoiceMask_PlayerMask struct {
	GameRulesMask    *int32 `protobuf:"varint,1,opt,name=game_rules_mask" json:"game_rules_mask,omitempty"`
	BanMasks         *int32 `protobuf:"varint,2,opt,name=ban_masks" json:"ban_masks,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_VoiceMask_PlayerMask) Reset()         { *m = CCSUsrMsg_VoiceMask_PlayerMask{} }
func (m *CCSUsrMsg_VoiceMask_PlayerMask) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VoiceMask_PlayerMask) ProtoMessage()    {}

func (m *CCSUsrMsg_VoiceMask_PlayerMask) GetGameRulesMask() int32 {
	if m != nil && m.GameRulesMask != nil {
		return *m.GameRulesMask
	}
	return 0
}

func (m *CCSUsrMsg_VoiceMask_PlayerMask) GetBanMasks() int32 {
	if m != nil && m.BanMasks != nil {
		return *m.BanMasks
	}
	return 0
}

type CCSUsrMsg_Damage struct {
	Amount            *int32                         `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	InflictorWorldPos *netmessages_public.CMsgVector `protobuf:"bytes,2,opt,name=inflictor_world_pos" json:"inflictor_world_pos,omitempty"`
	XXX_unrecognized  []byte                         `json:"-"`
}

func (m *CCSUsrMsg_Damage) Reset()         { *m = CCSUsrMsg_Damage{} }
func (m *CCSUsrMsg_Damage) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_Damage) ProtoMessage()    {}

func (m *CCSUsrMsg_Damage) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *CCSUsrMsg_Damage) GetInflictorWorldPos() *netmessages_public.CMsgVector {
	if m != nil {
		return m.InflictorWorldPos
	}
	return nil
}

type CCSUsrMsg_RadioText struct {
	MsgDst           *int32   `protobuf:"varint,1,opt,name=msg_dst" json:"msg_dst,omitempty"`
	Client           *int32   `protobuf:"varint,2,opt,name=client" json:"client,omitempty"`
	MsgName          *string  `protobuf:"bytes,3,opt,name=msg_name" json:"msg_name,omitempty"`
	Params           []string `protobuf:"bytes,4,rep,name=params" json:"params,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_RadioText) Reset()         { *m = CCSUsrMsg_RadioText{} }
func (m *CCSUsrMsg_RadioText) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_RadioText) ProtoMessage()    {}

func (m *CCSUsrMsg_RadioText) GetMsgDst() int32 {
	if m != nil && m.MsgDst != nil {
		return *m.MsgDst
	}
	return 0
}

func (m *CCSUsrMsg_RadioText) GetClient() int32 {
	if m != nil && m.Client != nil {
		return *m.Client
	}
	return 0
}

func (m *CCSUsrMsg_RadioText) GetMsgName() string {
	if m != nil && m.MsgName != nil {
		return *m.MsgName
	}
	return ""
}

func (m *CCSUsrMsg_RadioText) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type CCSUsrMsg_HintText struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_HintText) Reset()         { *m = CCSUsrMsg_HintText{} }
func (m *CCSUsrMsg_HintText) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_HintText) ProtoMessage()    {}

func (m *CCSUsrMsg_HintText) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type CCSUsrMsg_KeyHintText struct {
	Hints            []string `protobuf:"bytes,1,rep,name=hints" json:"hints,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_KeyHintText) Reset()         { *m = CCSUsrMsg_KeyHintText{} }
func (m *CCSUsrMsg_KeyHintText) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_KeyHintText) ProtoMessage()    {}

func (m *CCSUsrMsg_KeyHintText) GetHints() []string {
	if m != nil {
		return m.Hints
	}
	return nil
}

type CCSUsrMsg_ProcessSpottedEntityUpdate struct {
	NewUpdate        *bool                                                       `protobuf:"varint,1,opt,name=new_update" json:"new_update,omitempty"`
	EntityUpdates    []*CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate `protobuf:"bytes,2,rep,name=entity_updates" json:"entity_updates,omitempty"`
	XXX_unrecognized []byte                                                      `json:"-"`
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate) Reset()         { *m = CCSUsrMsg_ProcessSpottedEntityUpdate{} }
func (m *CCSUsrMsg_ProcessSpottedEntityUpdate) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ProcessSpottedEntityUpdate) ProtoMessage()    {}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate) GetNewUpdate() bool {
	if m != nil && m.NewUpdate != nil {
		return *m.NewUpdate
	}
	return false
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate) GetEntityUpdates() []*CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate {
	if m != nil {
		return m.EntityUpdates
	}
	return nil
}

type CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate struct {
	EntityIdx        *int32 `protobuf:"varint,1,opt,name=entity_idx" json:"entity_idx,omitempty"`
	ClassId          *int32 `protobuf:"varint,2,opt,name=class_id" json:"class_id,omitempty"`
	OriginX          *int32 `protobuf:"varint,3,opt,name=origin_x" json:"origin_x,omitempty"`
	OriginY          *int32 `protobuf:"varint,4,opt,name=origin_y" json:"origin_y,omitempty"`
	OriginZ          *int32 `protobuf:"varint,5,opt,name=origin_z" json:"origin_z,omitempty"`
	AngleY           *int32 `protobuf:"varint,6,opt,name=angle_y" json:"angle_y,omitempty"`
	Defuser          *bool  `protobuf:"varint,7,opt,name=defuser" json:"defuser,omitempty"`
	PlayerHasDefuser *bool  `protobuf:"varint,8,opt,name=player_has_defuser" json:"player_has_defuser,omitempty"`
	PlayerHasC4      *bool  `protobuf:"varint,9,opt,name=player_has_c4" json:"player_has_c4,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) Reset() {
	*m = CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate{}
}
func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) String() string {
	return proto.CompactTextString(m)
}
func (*CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) ProtoMessage() {}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetEntityIdx() int32 {
	if m != nil && m.EntityIdx != nil {
		return *m.EntityIdx
	}
	return 0
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetClassId() int32 {
	if m != nil && m.ClassId != nil {
		return *m.ClassId
	}
	return 0
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetOriginX() int32 {
	if m != nil && m.OriginX != nil {
		return *m.OriginX
	}
	return 0
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetOriginY() int32 {
	if m != nil && m.OriginY != nil {
		return *m.OriginY
	}
	return 0
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetOriginZ() int32 {
	if m != nil && m.OriginZ != nil {
		return *m.OriginZ
	}
	return 0
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetAngleY() int32 {
	if m != nil && m.AngleY != nil {
		return *m.AngleY
	}
	return 0
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetDefuser() bool {
	if m != nil && m.Defuser != nil {
		return *m.Defuser
	}
	return false
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetPlayerHasDefuser() bool {
	if m != nil && m.PlayerHasDefuser != nil {
		return *m.PlayerHasDefuser
	}
	return false
}

func (m *CCSUsrMsg_ProcessSpottedEntityUpdate_SpottedEntityUpdate) GetPlayerHasC4() bool {
	if m != nil && m.PlayerHasC4 != nil {
		return *m.PlayerHasC4
	}
	return false
}

type CCSUsrMsg_ReloadEffect struct {
	Entidx           *int32 `protobuf:"varint,1,opt,name=entidx" json:"entidx,omitempty"`
	Actanim          *int32 `protobuf:"varint,2,opt,name=actanim" json:"actanim,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_ReloadEffect) Reset()         { *m = CCSUsrMsg_ReloadEffect{} }
func (m *CCSUsrMsg_ReloadEffect) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ReloadEffect) ProtoMessage()    {}

func (m *CCSUsrMsg_ReloadEffect) GetEntidx() int32 {
	if m != nil && m.Entidx != nil {
		return *m.Entidx
	}
	return 0
}

func (m *CCSUsrMsg_ReloadEffect) GetActanim() int32 {
	if m != nil && m.Actanim != nil {
		return *m.Actanim
	}
	return 0
}

type CCSUsrMsg_AdjustMoney struct {
	Amount           *int32 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_AdjustMoney) Reset()         { *m = CCSUsrMsg_AdjustMoney{} }
func (m *CCSUsrMsg_AdjustMoney) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_AdjustMoney) ProtoMessage()    {}

func (m *CCSUsrMsg_AdjustMoney) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type CCSUsrMsg_KillCam struct {
	ObsMode          *int32 `protobuf:"varint,1,opt,name=obs_mode" json:"obs_mode,omitempty"`
	FirstTarget      *int32 `protobuf:"varint,2,opt,name=first_target" json:"first_target,omitempty"`
	SecondTarget     *int32 `protobuf:"varint,3,opt,name=second_target" json:"second_target,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_KillCam) Reset()         { *m = CCSUsrMsg_KillCam{} }
func (m *CCSUsrMsg_KillCam) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_KillCam) ProtoMessage()    {}

func (m *CCSUsrMsg_KillCam) GetObsMode() int32 {
	if m != nil && m.ObsMode != nil {
		return *m.ObsMode
	}
	return 0
}

func (m *CCSUsrMsg_KillCam) GetFirstTarget() int32 {
	if m != nil && m.FirstTarget != nil {
		return *m.FirstTarget
	}
	return 0
}

func (m *CCSUsrMsg_KillCam) GetSecondTarget() int32 {
	if m != nil && m.SecondTarget != nil {
		return *m.SecondTarget
	}
	return 0
}

type CCSUsrMsg_DesiredTimescale struct {
	DesiredTimescale    *float32 `protobuf:"fixed32,1,opt,name=desired_timescale" json:"desired_timescale,omitempty"`
	DurationRealtimeSec *float32 `protobuf:"fixed32,2,opt,name=duration_realtime_sec" json:"duration_realtime_sec,omitempty"`
	InterpolatorType    *int32   `protobuf:"varint,3,opt,name=interpolator_type" json:"interpolator_type,omitempty"`
	StartBlendTime      *float32 `protobuf:"fixed32,4,opt,name=start_blend_time" json:"start_blend_time,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *CCSUsrMsg_DesiredTimescale) Reset()         { *m = CCSUsrMsg_DesiredTimescale{} }
func (m *CCSUsrMsg_DesiredTimescale) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_DesiredTimescale) ProtoMessage()    {}

func (m *CCSUsrMsg_DesiredTimescale) GetDesiredTimescale() float32 {
	if m != nil && m.DesiredTimescale != nil {
		return *m.DesiredTimescale
	}
	return 0
}

func (m *CCSUsrMsg_DesiredTimescale) GetDurationRealtimeSec() float32 {
	if m != nil && m.DurationRealtimeSec != nil {
		return *m.DurationRealtimeSec
	}
	return 0
}

func (m *CCSUsrMsg_DesiredTimescale) GetInterpolatorType() int32 {
	if m != nil && m.InterpolatorType != nil {
		return *m.InterpolatorType
	}
	return 0
}

func (m *CCSUsrMsg_DesiredTimescale) GetStartBlendTime() float32 {
	if m != nil && m.StartBlendTime != nil {
		return *m.StartBlendTime
	}
	return 0
}

type CCSUsrMsg_CurrentTimescale struct {
	CurTimescale     *float32 `protobuf:"fixed32,1,opt,name=cur_timescale" json:"cur_timescale,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_CurrentTimescale) Reset()         { *m = CCSUsrMsg_CurrentTimescale{} }
func (m *CCSUsrMsg_CurrentTimescale) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_CurrentTimescale) ProtoMessage()    {}

func (m *CCSUsrMsg_CurrentTimescale) GetCurTimescale() float32 {
	if m != nil && m.CurTimescale != nil {
		return *m.CurTimescale
	}
	return 0
}

type CCSUsrMsg_AchievementEvent struct {
	Achievement      *int32 `protobuf:"varint,1,opt,name=achievement" json:"achievement,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	UserId           *int32 `protobuf:"varint,3,opt,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_AchievementEvent) Reset()         { *m = CCSUsrMsg_AchievementEvent{} }
func (m *CCSUsrMsg_AchievementEvent) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_AchievementEvent) ProtoMessage()    {}

func (m *CCSUsrMsg_AchievementEvent) GetAchievement() int32 {
	if m != nil && m.Achievement != nil {
		return *m.Achievement
	}
	return 0
}

func (m *CCSUsrMsg_AchievementEvent) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *CCSUsrMsg_AchievementEvent) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type CCSUsrMsg_MatchEndConditions struct {
	Fraglimit        *int32 `protobuf:"varint,1,opt,name=fraglimit" json:"fraglimit,omitempty"`
	MpMaxrounds      *int32 `protobuf:"varint,2,opt,name=mp_maxrounds" json:"mp_maxrounds,omitempty"`
	MpWinlimit       *int32 `protobuf:"varint,3,opt,name=mp_winlimit" json:"mp_winlimit,omitempty"`
	MpTimelimit      *int32 `protobuf:"varint,4,opt,name=mp_timelimit" json:"mp_timelimit,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_MatchEndConditions) Reset()         { *m = CCSUsrMsg_MatchEndConditions{} }
func (m *CCSUsrMsg_MatchEndConditions) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_MatchEndConditions) ProtoMessage()    {}

func (m *CCSUsrMsg_MatchEndConditions) GetFraglimit() int32 {
	if m != nil && m.Fraglimit != nil {
		return *m.Fraglimit
	}
	return 0
}

func (m *CCSUsrMsg_MatchEndConditions) GetMpMaxrounds() int32 {
	if m != nil && m.MpMaxrounds != nil {
		return *m.MpMaxrounds
	}
	return 0
}

func (m *CCSUsrMsg_MatchEndConditions) GetMpWinlimit() int32 {
	if m != nil && m.MpWinlimit != nil {
		return *m.MpWinlimit
	}
	return 0
}

func (m *CCSUsrMsg_MatchEndConditions) GetMpTimelimit() int32 {
	if m != nil && m.MpTimelimit != nil {
		return *m.MpTimelimit
	}
	return 0
}

type CCSUsrMsg_DisplayInventory struct {
	Display          *bool  `protobuf:"varint,1,opt,name=display" json:"display,omitempty"`
	UserId           *int32 `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_DisplayInventory) Reset()         { *m = CCSUsrMsg_DisplayInventory{} }
func (m *CCSUsrMsg_DisplayInventory) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_DisplayInventory) ProtoMessage()    {}

func (m *CCSUsrMsg_DisplayInventory) GetDisplay() bool {
	if m != nil && m.Display != nil {
		return *m.Display
	}
	return false
}

func (m *CCSUsrMsg_DisplayInventory) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type CCSUsrMsg_CallVoteFailed struct {
	Reason           *int32 `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
	Time             *int32 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_CallVoteFailed) Reset()         { *m = CCSUsrMsg_CallVoteFailed{} }
func (m *CCSUsrMsg_CallVoteFailed) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_CallVoteFailed) ProtoMessage()    {}

func (m *CCSUsrMsg_CallVoteFailed) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *CCSUsrMsg_CallVoteFailed) GetTime() int32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type CCSUsrMsg_VoteStart struct {
	Team             *int32  `protobuf:"varint,1,opt,name=team" json:"team,omitempty"`
	EntIdx           *int32  `protobuf:"varint,2,opt,name=ent_idx" json:"ent_idx,omitempty"`
	VoteType         *int32  `protobuf:"varint,3,opt,name=vote_type" json:"vote_type,omitempty"`
	DispStr          *string `protobuf:"bytes,4,opt,name=disp_str" json:"disp_str,omitempty"`
	DetailsStr       *string `protobuf:"bytes,5,opt,name=details_str" json:"details_str,omitempty"`
	OtherTeamStr     *string `protobuf:"bytes,6,opt,name=other_team_str" json:"other_team_str,omitempty"`
	IsYesNoVote      *bool   `protobuf:"varint,7,opt,name=is_yes_no_vote" json:"is_yes_no_vote,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_VoteStart) Reset()         { *m = CCSUsrMsg_VoteStart{} }
func (m *CCSUsrMsg_VoteStart) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VoteStart) ProtoMessage()    {}

func (m *CCSUsrMsg_VoteStart) GetTeam() int32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

func (m *CCSUsrMsg_VoteStart) GetEntIdx() int32 {
	if m != nil && m.EntIdx != nil {
		return *m.EntIdx
	}
	return 0
}

func (m *CCSUsrMsg_VoteStart) GetVoteType() int32 {
	if m != nil && m.VoteType != nil {
		return *m.VoteType
	}
	return 0
}

func (m *CCSUsrMsg_VoteStart) GetDispStr() string {
	if m != nil && m.DispStr != nil {
		return *m.DispStr
	}
	return ""
}

func (m *CCSUsrMsg_VoteStart) GetDetailsStr() string {
	if m != nil && m.DetailsStr != nil {
		return *m.DetailsStr
	}
	return ""
}

func (m *CCSUsrMsg_VoteStart) GetOtherTeamStr() string {
	if m != nil && m.OtherTeamStr != nil {
		return *m.OtherTeamStr
	}
	return ""
}

func (m *CCSUsrMsg_VoteStart) GetIsYesNoVote() bool {
	if m != nil && m.IsYesNoVote != nil {
		return *m.IsYesNoVote
	}
	return false
}

type CCSUsrMsg_VotePass struct {
	Team             *int32  `protobuf:"varint,1,opt,name=team" json:"team,omitempty"`
	VoteType         *int32  `protobuf:"varint,2,opt,name=vote_type" json:"vote_type,omitempty"`
	DispStr          *string `protobuf:"bytes,3,opt,name=disp_str" json:"disp_str,omitempty"`
	DetailsStr       *string `protobuf:"bytes,4,opt,name=details_str" json:"details_str,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_VotePass) Reset()         { *m = CCSUsrMsg_VotePass{} }
func (m *CCSUsrMsg_VotePass) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VotePass) ProtoMessage()    {}

func (m *CCSUsrMsg_VotePass) GetTeam() int32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

func (m *CCSUsrMsg_VotePass) GetVoteType() int32 {
	if m != nil && m.VoteType != nil {
		return *m.VoteType
	}
	return 0
}

func (m *CCSUsrMsg_VotePass) GetDispStr() string {
	if m != nil && m.DispStr != nil {
		return *m.DispStr
	}
	return ""
}

func (m *CCSUsrMsg_VotePass) GetDetailsStr() string {
	if m != nil && m.DetailsStr != nil {
		return *m.DetailsStr
	}
	return ""
}

type CCSUsrMsg_VoteFailed struct {
	Team             *int32 `protobuf:"varint,1,opt,name=team" json:"team,omitempty"`
	Reason           *int32 `protobuf:"varint,2,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_VoteFailed) Reset()         { *m = CCSUsrMsg_VoteFailed{} }
func (m *CCSUsrMsg_VoteFailed) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VoteFailed) ProtoMessage()    {}

func (m *CCSUsrMsg_VoteFailed) GetTeam() int32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

func (m *CCSUsrMsg_VoteFailed) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type CCSUsrMsg_VoteSetup struct {
	PotentialIssues  []string `protobuf:"bytes,1,rep,name=potential_issues" json:"potential_issues,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CCSUsrMsg_VoteSetup) Reset()         { *m = CCSUsrMsg_VoteSetup{} }
func (m *CCSUsrMsg_VoteSetup) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_VoteSetup) ProtoMessage()    {}

func (m *CCSUsrMsg_VoteSetup) GetPotentialIssues() []string {
	if m != nil {
		return m.PotentialIssues
	}
	return nil
}

type CCSUsrMsg_SendLastKillerDamageToClient struct {
	NumHitsGiven     *int32 `protobuf:"varint,1,opt,name=num_hits_given" json:"num_hits_given,omitempty"`
	DamageGiven      *int32 `protobuf:"varint,2,opt,name=damage_given" json:"damage_given,omitempty"`
	NumHitsTaken     *int32 `protobuf:"varint,3,opt,name=num_hits_taken" json:"num_hits_taken,omitempty"`
	DamageTaken      *int32 `protobuf:"varint,4,opt,name=damage_taken" json:"damage_taken,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_SendLastKillerDamageToClient) Reset() {
	*m = CCSUsrMsg_SendLastKillerDamageToClient{}
}
func (m *CCSUsrMsg_SendLastKillerDamageToClient) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_SendLastKillerDamageToClient) ProtoMessage()    {}

func (m *CCSUsrMsg_SendLastKillerDamageToClient) GetNumHitsGiven() int32 {
	if m != nil && m.NumHitsGiven != nil {
		return *m.NumHitsGiven
	}
	return 0
}

func (m *CCSUsrMsg_SendLastKillerDamageToClient) GetDamageGiven() int32 {
	if m != nil && m.DamageGiven != nil {
		return *m.DamageGiven
	}
	return 0
}

func (m *CCSUsrMsg_SendLastKillerDamageToClient) GetNumHitsTaken() int32 {
	if m != nil && m.NumHitsTaken != nil {
		return *m.NumHitsTaken
	}
	return 0
}

func (m *CCSUsrMsg_SendLastKillerDamageToClient) GetDamageTaken() int32 {
	if m != nil && m.DamageTaken != nil {
		return *m.DamageTaken
	}
	return 0
}

type CCSUsrMsg_ItemPickup struct {
	Item             *string `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_ItemPickup) Reset()         { *m = CCSUsrMsg_ItemPickup{} }
func (m *CCSUsrMsg_ItemPickup) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ItemPickup) ProtoMessage()    {}

func (m *CCSUsrMsg_ItemPickup) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

type CCSUsrMsg_ShowMenu struct {
	BitsValidSlots   *int32  `protobuf:"varint,1,opt,name=bits_valid_slots" json:"bits_valid_slots,omitempty"`
	DisplayTime      *int32  `protobuf:"varint,2,opt,name=display_time" json:"display_time,omitempty"`
	MenuString       *string `protobuf:"bytes,3,opt,name=menu_string" json:"menu_string,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_ShowMenu) Reset()         { *m = CCSUsrMsg_ShowMenu{} }
func (m *CCSUsrMsg_ShowMenu) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ShowMenu) ProtoMessage()    {}

func (m *CCSUsrMsg_ShowMenu) GetBitsValidSlots() int32 {
	if m != nil && m.BitsValidSlots != nil {
		return *m.BitsValidSlots
	}
	return 0
}

func (m *CCSUsrMsg_ShowMenu) GetDisplayTime() int32 {
	if m != nil && m.DisplayTime != nil {
		return *m.DisplayTime
	}
	return 0
}

func (m *CCSUsrMsg_ShowMenu) GetMenuString() string {
	if m != nil && m.MenuString != nil {
		return *m.MenuString
	}
	return ""
}

type CCSUsrMsg_BarTime struct {
	Time             *string `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_BarTime) Reset()         { *m = CCSUsrMsg_BarTime{} }
func (m *CCSUsrMsg_BarTime) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_BarTime) ProtoMessage()    {}

func (m *CCSUsrMsg_BarTime) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

type CCSUsrMsg_AmmoDenied struct {
	AmmoIdx          *int32 `protobuf:"varint,1,opt,name=ammoIdx" json:"ammoIdx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_AmmoDenied) Reset()         { *m = CCSUsrMsg_AmmoDenied{} }
func (m *CCSUsrMsg_AmmoDenied) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_AmmoDenied) ProtoMessage()    {}

func (m *CCSUsrMsg_AmmoDenied) GetAmmoIdx() int32 {
	if m != nil && m.AmmoIdx != nil {
		return *m.AmmoIdx
	}
	return 0
}

type CCSUsrMsg_MarkAchievement struct {
	Achievement      *string `protobuf:"bytes,1,opt,name=achievement" json:"achievement,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_MarkAchievement) Reset()         { *m = CCSUsrMsg_MarkAchievement{} }
func (m *CCSUsrMsg_MarkAchievement) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_MarkAchievement) ProtoMessage()    {}

func (m *CCSUsrMsg_MarkAchievement) GetAchievement() string {
	if m != nil && m.Achievement != nil {
		return *m.Achievement
	}
	return ""
}

type CCSUsrMsg_ItemDrop struct {
	Itemid           *int64 `protobuf:"varint,1,opt,name=itemid" json:"itemid,omitempty"`
	Death            *bool  `protobuf:"varint,2,opt,name=death" json:"death,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_ItemDrop) Reset()         { *m = CCSUsrMsg_ItemDrop{} }
func (m *CCSUsrMsg_ItemDrop) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ItemDrop) ProtoMessage()    {}

func (m *CCSUsrMsg_ItemDrop) GetItemid() int64 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func (m *CCSUsrMsg_ItemDrop) GetDeath() bool {
	if m != nil && m.Death != nil {
		return *m.Death
	}
	return false
}

type CCSUsrMsg_GlowPropTurnOff struct {
	Entidx           *int32 `protobuf:"varint,1,opt,name=entidx" json:"entidx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_GlowPropTurnOff) Reset()         { *m = CCSUsrMsg_GlowPropTurnOff{} }
func (m *CCSUsrMsg_GlowPropTurnOff) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_GlowPropTurnOff) ProtoMessage()    {}

func (m *CCSUsrMsg_GlowPropTurnOff) GetEntidx() int32 {
	if m != nil && m.Entidx != nil {
		return *m.Entidx
	}
	return 0
}

type CCSUsrMsg_RoundBackupFilenames struct {
	Count            *int32  `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Index            *int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Filename         *string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	Nicename         *string `protobuf:"bytes,4,opt,name=nicename" json:"nicename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCSUsrMsg_RoundBackupFilenames) Reset()         { *m = CCSUsrMsg_RoundBackupFilenames{} }
func (m *CCSUsrMsg_RoundBackupFilenames) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_RoundBackupFilenames) ProtoMessage()    {}

func (m *CCSUsrMsg_RoundBackupFilenames) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *CCSUsrMsg_RoundBackupFilenames) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CCSUsrMsg_RoundBackupFilenames) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *CCSUsrMsg_RoundBackupFilenames) GetNicename() string {
	if m != nil && m.Nicename != nil {
		return *m.Nicename
	}
	return ""
}

type CCSUsrMsg_ResetHud struct {
	Reset_           *bool  `protobuf:"varint,1,opt,name=reset" json:"reset,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_ResetHud) Reset()         { *m = CCSUsrMsg_ResetHud{} }
func (m *CCSUsrMsg_ResetHud) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ResetHud) ProtoMessage()    {}

func (m *CCSUsrMsg_ResetHud) GetReset_() bool {
	if m != nil && m.Reset_ != nil {
		return *m.Reset_
	}
	return false
}

type CCSUsrMsg_GameTitle struct {
	Dummy            *int32 `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_GameTitle) Reset()         { *m = CCSUsrMsg_GameTitle{} }
func (m *CCSUsrMsg_GameTitle) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_GameTitle) ProtoMessage()    {}

func (m *CCSUsrMsg_GameTitle) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

type CCSUsrMsg_RequestState struct {
	Dummy            *int32 `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_RequestState) Reset()         { *m = CCSUsrMsg_RequestState{} }
func (m *CCSUsrMsg_RequestState) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_RequestState) ProtoMessage()    {}

func (m *CCSUsrMsg_RequestState) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

type CCSUsrMsg_StopSpectatorMode struct {
	Dummy            *int32 `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_StopSpectatorMode) Reset()         { *m = CCSUsrMsg_StopSpectatorMode{} }
func (m *CCSUsrMsg_StopSpectatorMode) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_StopSpectatorMode) ProtoMessage()    {}

func (m *CCSUsrMsg_StopSpectatorMode) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

type CCSUsrMsg_DisconnectToLobby struct {
	Dummy            *int32 `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_DisconnectToLobby) Reset()         { *m = CCSUsrMsg_DisconnectToLobby{} }
func (m *CCSUsrMsg_DisconnectToLobby) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_DisconnectToLobby) ProtoMessage()    {}

func (m *CCSUsrMsg_DisconnectToLobby) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

type CCSUsrMsg_WarmupHasEnded struct {
	Dummy            *int32 `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_WarmupHasEnded) Reset()         { *m = CCSUsrMsg_WarmupHasEnded{} }
func (m *CCSUsrMsg_WarmupHasEnded) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_WarmupHasEnded) ProtoMessage()    {}

func (m *CCSUsrMsg_WarmupHasEnded) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

type CCSUsrMsg_ClientInfo struct {
	Dummy            *int32 `protobuf:"varint,1,opt,name=dummy" json:"dummy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCSUsrMsg_ClientInfo) Reset()         { *m = CCSUsrMsg_ClientInfo{} }
func (m *CCSUsrMsg_ClientInfo) String() string { return proto.CompactTextString(m) }
func (*CCSUsrMsg_ClientInfo) ProtoMessage()    {}

func (m *CCSUsrMsg_ClientInfo) GetDummy() int32 {
	if m != nil && m.Dummy != nil {
		return *m.Dummy
	}
	return 0
}

func init() {
	proto.RegisterEnum("ECstrike15UserMessages", ECstrike15UserMessages_name, ECstrike15UserMessages_value)
}
